# Generated by Django 3.1.5 on 2021-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(default='lorem ipsum', max_length=512),
            preserve_default=False,
        ),
    ]
