# Generated by Django 3.1.5 on 2021-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210125_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('LF', 'Life'), ('SC', 'School'), ('TE', 'Tech'), ('PR', 'Professional')], default='LF', max_length=16),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
