# Generated by Django 3.1.4 on 2021-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
