# Generated by Django 3.1.5 on 2021-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
