# Generated by Django 3.1.4 on 2021-02-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210205_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Auction'),
        ),
    ]
